[package]
name = "ecss"
version = "0.1.0"
authors = ["Matthew Smeraglia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecss_component_derive = {path="ecss_component_derive"}